# Generated by Django 5.2.4 on 2025-07-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
    ]
