# Generated by Django 5.2.4 on 2025-07-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0004_alter_actor_id_alter_category_id_alter_director_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='actor_first_name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='last_name',
            new_name='actor_last_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='first_name',
            new_name='director_first_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='last_name',
            new_name='director_last_name',
        ),
    ]
