# Generated by Django 5.2.4 on 2025-07-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0005_rename_first_name_actor_actor_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actor_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='actor_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='director_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='director_last_name',
            new_name='last_name',
        ),
    ]
