# Generated by Django 5.2.4 on 2025-07-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0006_rename_actor_first_name_actor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='film_rate_api.category'),
        ),
    ]
