# Generated by Django 5.2.4 on 2025-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0007_remove_film_category_film_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='created_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Created Users UUID'),
        ),
        migrations.AddField(
            model_name='actor',
            name='updated_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Updated Users UUID'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Created Users UUID'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Updated Users UUID'),
        ),
        migrations.AddField(
            model_name='director',
            name='created_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Created Users UUID'),
        ),
        migrations.AddField(
            model_name='director',
            name='updated_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Updated Users UUID'),
        ),
        migrations.AddField(
            model_name='film',
            name='created_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Created Users UUID'),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_by',
            field=models.UUIDField(default='161b80fd31ec404d84b1a465b96874ea', editable=False, verbose_name='Updated Users UUID'),
        ),
    ]
