# Generated by Django 5.2.4 on 2025-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_rate_api', '0008_actor_created_by_actor_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='created_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Created Users UUID'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Updated Users UUID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Created Users UUID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Updated Users UUID'),
        ),
        migrations.AlterField(
            model_name='director',
            name='created_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Created Users UUID'),
        ),
        migrations.AlterField(
            model_name='director',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Updated Users UUID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Created Users UUID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True, verbose_name='Updated Users UUID'),
        ),
    ]
